// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Di8SItXLryZAHecgdjmd0PGNGRQkHe0',
    appId: '1:793765751215:web:8447f6a4017636871ce75a',
    messagingSenderId: '793765751215',
    projectId: 'genai-gp',
    authDomain: 'genai-gp.firebaseapp.com',
    databaseURL: 'https://genai-gp-default-rtdb.firebaseio.com',
    storageBucket: 'genai-gp.appspot.com',
    measurementId: 'G-73EK1HZSRS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Di8SItXLryZAHecgdjmd0PGNGRQkHe0',
    appId: '1:793765751215:web:00314483f7bfccf91ce75a',
    messagingSenderId: '793765751215',
    projectId: 'genai-gp',
    authDomain: 'genai-gp.firebaseapp.com',
    databaseURL: 'https://genai-gp-default-rtdb.firebaseio.com',
    storageBucket: 'genai-gp.appspot.com',
    measurementId: 'G-M3TD2EE557',
  );

}